#!/usr/bin/env bash
set -e -o pipefail

PREFIX="/vagrant/target/"

PLEX="${PREFIX}plexmediaserver"
VERSION_FILE="${PREFIX}version.json"
A_WEEK_AGO=$(date +%s -d '7 days ago')
RELEASE_PATH='.nas["Western Digital"]["release_date"]'
VERSION_PATH='.nas["Western Digital"]["version"]'
BINARY_PATH='.nas["Western Digital"]["releases"][]|select(.distro=="wd-mirrorgen2")|.url'

mkdir -p "$PREFIX"

if [ ! -f $VERSION_FILE ] || (( $(jq -r "$RELEASE_PATH" "$VERSION_FILE") <= $A_WEEK_AGO )); then
  echo "Fetching latest version data."
  rm -f "$VERSION_FILE"
  wget -q -O "$VERSION_FILE" "https://plex.tv/api/downloads/5.json?_=$(date +%s%N | cut -b1-13)"
else
  echo "Reusing existing version data."
fi

PLEX_BINARY_URL=$(jq -r "$BINARY_PATH" "$VERSION_FILE")
VERSION=$(jq -r "$VERSION_PATH" "$VERSION_FILE")
PLEX_BINARY="${PREFIX}$(basename $PLEX_BINARY_URL)"
REPACKAGED_BINARY="${PLEX_BINARY/MirrorGen2/}"

if [ ! -f $PLEX_BINARY ]; then
  echo "Fetching latest Plex Media Server binary."
  wget -q -O "$PLEX_BINARY" "$PLEX_BINARY_URL"
else
  echo "Reusing existing Plex Media Server binary."
fi

if [ ! -f $REPACKAGED_BINARY ]; then
  rm -rf "$PLEX" "${PLEX}.tar.gz"
  echo "Extracting binary."
  dd if=$PLEX_BINARY of="${PLEX}.tar.gz" bs=200 skip=1 status=none
  echo "Extracting code."
  tar -C "$PREFIX" -xzf "${PLEX}.tar.gz"
  echo "Repackaging binary."
  TMP_BINARY="${PREFIX}WDMyCloud_plexmediaserver_${VERSION%%-*}.bin($(date +%m%d%Y))"
  (cd "${PLEX}" && mkapkg -E -s -m WDMyCloud 1>/dev/null)
  mv $TMP_BINARY $REPACKAGED_BINARY
  rm -rf "$PLEX" "${PLEX}.tar.gz"
  echo "Latest binary repackaged: ${REPACKAGED_BINARY}"
else
  echo "Latest repackaged binary: ${REPACKAGED_BINARY}"
fi
